type: 'python'

services:
  db1:
    type: 'postgresql'
    size: 2Gi
    backup: false
  cache:
    type: 'redis'
    size: 2Gi
    backup: false
  
resources:
  cpu: "1"
  memory: "1Gi"


envs:  
  DJANGO_SECRET_KEY: "uz!$0&59^!n2!(cg153h(6edt#&@#b^yktezs45=fp-(votmy+"
  DJANGO_ADMIN_URL: "admin-sb/"
  CELERY_BROKER_URL: "redis://:shapeblock@univ-python-0910-10-33-redis-master:6379/0"
  DJANGO_SETTINGS_MODULE: "config.settings.production"

workers:
  celery: {}
  celerybeat: {}

